# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb4cf318349159c54834d1895dc2a17492a49347d856f346e10d56c712395b9d33fd4acd1063e82e8f2c68934145312a074f14b992ea221f40b2eba0b565df5

test:
  secret_key_base: 3bf6419bcc2cadad66d28bf7bbeffe87496fd4bcbae1cce86fd9328be7116b20f39404f879ab3deda561c3c9d76bc1f429241745caae989f98fb380cb76d5a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
